### PR TITLE
Proposal: Fix problem on autostart kue

### PR DESCRIPTION
**Pull request by Alvadorn**
As @devglrd cited on [#6](https://github.com/erickponce/nestjs-kue/pull/6#issuecomment-517066203), I believe this could be a good way to fix the problem.

### CODE REVIEW

**Comment by devglrd** [comment]
It's working !

Hope it was merged fast !

**Comment by erickponce** [comment]
Hello there!

Thank you @devglrd for spotting this issue, and @Alvadorn for the quick PR!  🎉

**Comment by erickponce** [comment]
I just published version 0.3.2 in NPM

**Comment by devglrd** [comment]
I prepare a pr for support Redis Sentinel configuration in your package :) soon

**Pull request merged**
